-- NOTE: This creates the da_nba schema, and imports the play by play data for one game.

BEGIN;

CREATE SCHEMA IF NOT EXISTS da_nba;

CREATE TABLE IF NOT EXISTS da_nba.game0021600001 (
        F1 INTEGER PRIMARY KEY,
        EVENTMSGACTIONTYPE INTEGER,
        EVENTMSGTYPE INTEGER,
        EVENTNUM INTEGER,
        GAME_ID INTEGER,
        HOMEDESCRIPTION VARCHAR(100),
        NEUTRALDESCRIPTION VARCHAR(100),
        PCTIMESTRING TIME,
        PERIOD INTEGER,
        PERSON1TYPE FLOAT,
        PERSON2TYPE INTEGER,
        PERSON3TYPE INTEGER,
        PLAYER1_ID INTEGER,
		PLAYER1_NAME VARCHAR(40),
        PLAYER1_TEAM_ABBREVIATION VARCHAR(3),
        PLAYER1_TEAM_CITY VARCHAR(20),
        PLAYER1_TEAM_ID FLOAT,
        PLAYER1_TEAM_NICKNAME VARCHAR(20),
        PLAYER2_ID INTEGER,
	    PLAYER2_NAME VARCHAR(40),
        PLAYER2_TEAM_ABBREVIATION VARCHAR(3),
        PLAYER2_TEAM_CITY VARCHAR(20),
        PLAYER2_TEAM_ID FLOAT,
        PLAYER2_TEAM_NICKNAME VARCHAR(20),
        PLAYER3_ID INTEGER,
	    PLAYER3_NAME VARCHAR(40),
        PLAYER3_TEAM_ABBREVIATION VARCHAR(3),
        PLAYER3_TEAM_CITY VARCHAR(20),
        PLAYER3_TEAM_ID FLOAT,
        PLAYER3_TEAM_NICKNAME VARCHAR(20),
        SCORE VARCHAR(10),
        SCOREMARGIN VARCHAR(10),
        VISITORDESCRIPTION VARCHAR(100),
        WCTIMESTRING VARCHAR(10)
        );


DELETE FROM da_nba.game0021600001;

-- UPDATE THIS PATH:
COPY da_nba.game0021600001 FROM '/Users/shwang/Desktop/Data Analytics Class/NBA/2016-17/0021600001.csv'
WITH DELIMITER ',' CSV HEADER;


COMMIT;

SELECT * FROM da_nba.game0021600001
limit 10